import {
  addFundToList,
  createList,
  deleteList,
  getHolding,
  getFundDetail,
  getFundTrend,
  getFundAccumTrend,
  syncFundPingzhong,
  getStorageWarning,
  getAllLists,
  getListFundSummaries,
  getListFunds,
  renameList,
  reorderLists,
  removeFundFromList,
  searchFund,
  setHolding,
  clearHolding,
  setRefreshInterval,
} from "./useTauriApi";

export function useTauriCommands() {
  return {
    searchFund,
    getAllLists,
    createList,
    renameList,
    deleteList,
    addFundToList,
    removeFundFromList,
    getListFunds,
    getListFundSummaries,
    getFundDetail,
    getFundTrend,
    getFundAccumTrend,
    syncFundPingzhong,
    getStorageWarning,
    reorderLists,
    getHolding,
    setHolding,
    clearHolding,
    setRefreshInterval,
  };
}
